### ISSUE TITLE
Support Memcached 2.2.0 and up 

### ISSUE THREAD

**Issue by tiemevanveen** [GeckoPackages/GeckoSilexMemcacheService#6] opened 2016-03-04 11:55 UTC
~/GeckoSilexMemcacheService on master
         $ php --version
        PHP 5.6.18 (cli) (built: Feb  6 2016 06:53:53)
        Copyright (c) 1997-2016 The PHP Group
        Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
            with Xdebug v2.3.3, Copyright (c) 2002-2015, by Derick Rethans

    ~/GeckoSilexMemcacheService on master
         $ php -i | grep memcached
        /usr/local/etc/php/5.6/conf.d/ext-memcached.ini,
        PHP Warning:  Unknown: It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in Unknown on line 0
        memcached
        memcached support => enabled
        libmemcached version => 1.0.18
        memcached.compression_factor => 1.3 => 1.3
        memcached.compression_threshold => 2000 => 2000
        memcached.compression_type => fastlz => fastlz
        memcached.serializer => igbinary => igbinary
        memcached.sess_binary => no value => no value
        memcached.sess_lock_wait => 150000 => 150000
        memcached.sess_locking => 1 => 1
        memcached.sess_prefix => memc.sess.key. => memc.sess.key.
        Registered save handlers => files user memcache memcached
        
    ~/GeckoSilexMemcacheService on master
         $ phpunit
        PHPUnit 4.6.6 by Sebastian Bergmann and contributors.

        Configuration read from /Users/tieme/GeckoSilexMemcacheService/phpunit.xml.dist

        E........

        Time: 134 ms, Memory: 14.50Mb

        There was 1 error:

        1) MemcachedLoggingCompletenessTest::testMethodLogging
        Declaration of GeckoPackages\Silex\Services\Caching\Clients\MemcachedLogging::get() should be compatible with Memcached::get($key, $cache_cb = NULL, &$cas_token = NULL)

        /Users/tieme/GeckoSilexMemcacheService/src/Caching/Clients/MemcachedLogging.php:22
        /Users/tieme/GeckoSilexMemcacheService/tests/Caching/Tests/MemcachedLoggingCompletenessTest.php:27

        FAILURES!
        Tests: 9, Assertions: 54, Errors: 1.

Do I need a specific memcached version for this?

**Comment by tiemevanveen** [comment] 2016-03-04 11:57
Same on my vagrant box 

    [11:56 AM]-[vagrant@machine1]-[/var/www/testrepos/GeckoSilexMemcacheService]-[git 1.0]
    $ php --version
        PHP 7.0.4-1+deb.sury.org~trusty+1 (cli) ( NTS )
        Copyright (c) 1997-2016 The PHP Group
        Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
            with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

    [11:56 AM]-[vagrant@machine1]-[/var/www/testrepos/GeckoSilexMemcacheService]-[git 1.0]
    $ php -i | grep memcache
        44:/etc/php/7.0/cli/conf.d/25-memcached.ini,
        318:memcached
        320:memcached support => enabled
        322:libmemcached version => 1.0.18
        330:memcached.compression_factor => 1.3 => 1.3
        331:memcached.compression_threshold => 2000 => 2000
        332:memcached.compression_type => fastlz => fastlz
        333:memcached.default_binary_protocol => 0 => 0
        334:memcached.default_connect_timeout => 0 => 0
        335:memcached.default_consistent_hash => 0 => 0
        336:memcached.serializer => php => php
        337:memcached.sess_binary_protocol => 1 => 1
        338:memcached.sess_connect_timeout => 0 => 0
        339:memcached.sess_consistent_hash => 1 => 1
        340:memcached.sess_lock_expire => 0 => 0
        341:memcached.sess_lock_max_wait => not set => not set
        342:memcached.sess_lock_retries => 5 => 5
        343:memcached.sess_lock_wait => not set => not set
        344:memcached.sess_lock_wait_max => 2000 => 2000
        345:memcached.sess_lock_wait_min => 1000 => 1000
        346:memcached.sess_locking => 1 => 1
        347:memcached.sess_number_of_replicas => 0 => 0
        348:memcached.sess_persistent => 0 => 0
        349:memcached.sess_prefix => memc.sess. => memc.sess.
        350:memcached.sess_randomize_replica_read => 0 => 0
        351:memcached.sess_remove_failed_servers => 0 => 0
        352:memcached.sess_sasl_password => no value => no value
        353:memcached.sess_sasl_username => no value => no value
        354:memcached.sess_server_failure_limit => 0 => 0
        355:memcached.store_retry_count => 2 => 2
        652:Registered save handlers => files user memcached
        847:PWD => /var/www/testrepos/GeckoSilexMemcacheService
        883:$_SERVER['PWD'] => /var/www/testrepos/GeckoSilexMemcacheService

    [11:56 AM]-[vagrant@machine1]-[/var/www/testrepos/GeckoSilexMemcacheService]-[git 1.0]
    $ phpunit
        PHPUnit 5.2.9 by Sebastian Bergmann and contributors.

        E........                                                           9 / 9 (100%)

        Time: 115 ms, Memory: 8.00Mb

        There was 1 error:

        1) MemcachedLoggingCompletenessTest::testMethodLogging
        Declaration of GeckoPackages\Silex\Services\Caching\Clients\MemcachedLogging::get($key, callable $cache_cb = NULL, &$cas_token = NULL) should be compatible with Memcached::get($key, $cache_cb = NULL)

        /var/www/testrepos/GeckoSilexMemcacheService/src/Caching/Clients/MemcachedLogging.php:21
        /var/www/testrepos/GeckoSilexMemcacheService/tests/Caching/Tests/MemcachedLoggingCompletenessTest.php:27

        FAILURES!
        Tests: 9, Assertions: 54, Errors: 1.

**Comment by SpacePossum** [comment] 2016-03-04 12:23
Thanks for the report, I think this is the same issue:
https://github.com/GeckoPackages/GeckoMemcacheMock/pull/3

The problem is Memcached API has been changed between versions. Could you dump the API of the Memcached package you use? (maybe run the tests first of the mock, than we know its the same issue)

Beside the test failing, does the service still work for you?

**Comment by tiemevanveen** [comment] 2016-03-04 12:43
Mock tests: 

    PHPUnit 4.6.6 by Sebastian Bergmann and contributors.

    Configuration read from /Users/tieme/Projects/Repos/GeckoMemcacheMock/phpunit.xml.dist

    ...............................................................  63 / 122 ( 51%)
    ...........................................................

    Time: 4.23 seconds, Memory: 15.00Mb

    OK (122 tests, 923 assertions)

**Comment by tiemevanveen** [comment] 2016-03-04 12:44
> Beside the test failing, does the service still work for you?

Not sure, not in my tests.. but I think that is an issue with my phpunit setup. Checking now.

**Comment by SpacePossum** [comment] 2016-03-07 12:43
It seems Memcached (2.2.0b1) is alrady an issue.
https://travis-ci.org/GeckoPackages/GeckoMemcacheMock/jobs/114229116

**Comment by tiemevanveen** [comment] 2016-03-07 15:31
> It seems Memcached (2.2.0b1) is alrady an issue.
:( 

> Beside the test failing, does the service still work for you?
Did some more tests, yes the service still works for me :)

**Comment by SpacePossum** [comment] 2016-03-07 17:06
Good to hear. 
I hope to write support for more memchached versions in the near future, but only stable releases.

**Comment by tiemevanveen** [comment] 2016-03-07 19:30
:+1:

**Comment by tiemevanveen** [comment] 2016-05-09 21:47
> I hope to write support for more memchached versions in the near future, but only stable releases.

It looks like the current stable memcached.so version is already not supported. So how could we fix this? Duplicate the classes and change all method signatures? Or start a new release branch (v2.2?) in in git and change the class so it matches v2.2.0? I was looking for documentation on the v2.2.0 methods but could only find the old ones one http://php.net/manual/en/memcached.get.php .. 

But you probably already looked into this and know a bit better what the changes are? Changelog does [not really say a lot](https://pecl.php.net/package-changelog.php?package=memcached) :( Oh and haha check this [release msg](https://github.com/php-memcached-dev/php-memcached/releases/tag/2.2.0) for v.2.2.0.

**Comment by SpacePossum** [comment] 2016-05-09 22:08
It seems the are a bit of changes to the API, some of those are not documented. Besides the changes, the current stable is not documented very well...
for ref.: https://github.com/php-memcached-dev/php-memcached/issues/227 for getting the stables documented
and there is https://github.com/travis-ci/travis-ci/issues/5757 which I opened because a not stable version is used as default for HHVM by travis at the moment.
I'm still working on this in two ways:
- getting the docs in order of the memcached package
- supporting multiple memcached release (stables only)

it will take time though.. sorry for keep you wanting. 
Beside the tests failing it should however only effect the logger and nothing else (i.e. don't use the logger and you should be fine)

**Comment by tiemevanveen** [comment] 2016-05-09 22:11
Check.

No worries, no hurry.

**Comment by SpacePossum** [comment] 2016-07-28 10:06
closing because https://github.com/GeckoPackages/GeckoSilexMemcacheService/pull/12 is merged.
Please note that there is no 3.x tag.

**Closed by SpacePossum** 2016-07-28 10:06 UTC
Labels: bug

**Comment by tiemevanveen** [comment] 2016-11-20 21:08
\0/
